name: CI

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      GIT_TAG: ${{ steps.set-tag.outputs.GIT_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: xvfb-run -a pnpm test

      - name: Set GIT_TAG
        id: set-tag
        run: |
          git fetch --tags origin
          GIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -n "$GIT_TAG" ] && [ "$(git rev-list -n 1 $GIT_TAG 2>/dev/null || echo "")" = "$(git rev-parse HEAD)" ]; then
            echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_OUTPUT
          else
            echo "GIT_TAG=" >> $GITHUB_OUTPUT
          fi

  publish:
    needs: test
    if: startsWith(needs.test.outputs.GIT_TAG, 'v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Publish to Open VSX Registry
        run: pnpm run publish:open-vsx -p ${{ secrets.OPEN_VSX_TOKEN }}

      - name: Github Release
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
